use_frameworks!

target 'CGMathSwift_Example' do
	pod 'CGMathSwift', :path => '../'

	target 'CGMathSwift_Tests' do
		inherit! :search_paths

		pod 'CGMathSwift', :path => '../'
		pod 'Quick', '~> 0.10.0'
		pod 'Nimble', '~> 5.0'
	end
end
